### ISSUE TITLE
Cannot find module 'electron-reload' on windows

### ISSUE THREAD

**Issue by qfulsher** [joereynolds/fanbox#8]
I'm trying to run fanbox on 64 bit windows, it seems that it cannot find a module. Here is the full stack trace:

```
App threw an error during load
Error: Cannot find module 'electron-reload'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\inondle\AppData\Roaming\npm\node_modules\electron\dist\resources\elec
tron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\inondle\dev\fanbox\app\main.js:10:1)
    at Object.<anonymous> (C:\Users\inondle\dev\fanbox\app\main.js:51:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by joereynolds** [comment]
Hi @inondle,

I've pushed up a few changes that may solve this problem as a side effect.
If you could try again that'd be great.

Let me know if there're any problems.
Thanks!
Joe
